### ISSUE TITLE
Incompatible with Node 4.2.1

### ISSUE THREAD

**Issue by dga711** [mattcg/socks5-client#10]
Can't use it as an agent with request using Node 4.2.1
Example also doesnt work.

Proxy is a TOR proxy.

Edit: The issue is concerning socks5-http-client. But the problem seems to lie in this library.

**Comment by dga711** [comment]
I'm no expert with this but one thing i saw while trying to debug:
The last 2 bytes (Port) of the request to proxy are 0 80 . Shouldn't it be  LOWBYTE HIGHBYTE?

But this probably not what breaks it.

**Comment by wreckloose** [comment]
I've run into a similar (or perhaps the same) issue. The error message I'm getting seems to have something to do with the use of stream.Writable.cork(). Here's the error I'm getting:

TypeError: socket.cork is not a function
    at ClientRequest.OutgoingMessage._flush (_http_outgoing.js:642:14)
    at _http_client.js:148:10
    at Socks5ClientSocket.callSocketMethod (_http_client.js:513:7)
    at Socks5ClientSocket.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Socks5ClientSocket.emit (events.js:166:7)
    at Socks5ClientSocket.handleSocksConnectToHost (/usr/home/zuul/code/frigg/node_modules/socks5-http-client/node_modules/socks5-client/lib/Socks5ClientSocket.js:135:7) 

I'm not sure why cork() would be an issue, since I believe this was introduced in v0.12, which I was previously using without a problem. 

I don't know if this is happening during socket connection (see this thread [https://github.com/nodejs/node/pull/2960#discussion_r41955893]), or during a write, though I *have* found that if I change self.writeable to false on line 131 of Socket.js [https://github.com/mattcg/socks5-client/blob/master/lib/Socket.js#L131], then I no longer have the issue.

**Comment by wreckloose** [comment]
Also, I'm using FreeBSD. Not sure sure if it has anything to do with FreeBSD's use of TCP_NOPUSH in place of Linux's use of TCP_CORK.

**Comment by dga711** [comment]
Thanks for your input.
I don't think its a problem with FreeBSD. I get the same error on Win10/2008R2 when running the examples from the socks5-http-client project.

**Comment by mattcg** [comment]
This should have been fixed by #11. Will you re-test please?

**Comment by wreckloose** [comment]
Installing the latest version (1.1.2) has fixed my problem. Thanks!

**Comment by mattcg** [comment]
Fantastic, thank you for reporting! :sparkling_heart:
